### ISSUE TITLE
Run tests on one host and not the other?

### ISSUE THREAD

**Issue by nellshamrell** [newcontext/kitchen-terraform#44]
Hello!  

I am currently attempting to Test Drive a configuration which spins up multiple servers.  I would like to be able to run one group of tests on one server, and another on a second server.

I have two servers currently as part of my cluster.

1) A Chef Server
2) A Supermarket Server

I would like to be able to run some tests on the Chef Server (and NOT run them on the Supermarket Server) and then some tests on the Supermarket Server (and NOT on the Chef Server).

If I define my .kitchen.yml like this:
```
verifier:
  name: terraform
  format: doc
  groups:
  - name: default
    tests:
      - oauth
    hostnames: cluster_hostnames
    username: ubuntu
```

And then my output.tf file like this:
```
output "cluster_hostnames" {
  value = "${module.chef-server.chef_server_hostname},${module.supermarket-server.supermarket_server_hostname}"
}
```
Is there any way to specify that certain inspec tests should only be run on the chef server, and certain ones should only be run on the supermarket server?  Or would I need to create separate groups/suites - one for the chef_server, and one for the supermarket_server?

Thank you!

**Comment by nellshamrell** [comment]
Update: I tried defining the tests to run on the chef server and the tests to run on the supermarket server in separate groups like so:
```
---
driver:
  name: terraform

provisioner:
  name: terraform
  variable_files:
    - terraform.tfvars

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: ~/.aws/nshamrell-staging.pem

verifier:
  name: terraform
  format: doc
  groups:
  - name: chef_server
    tests:
      - chef_server_config
    hostnames: chef_server_hostname
    username: ubuntu
  - name: supermarket_server
    tests:
      - supermarket_server_config
    hostnames: supermarket_server_hostname
    username: ubuntu

suites:
  - name: chef_server
    run_list:
    attributes:
  - name: supermarket_server
    run_list:
    attributes:
```

Here is what my output.tf looks like:
```
output "chef_server_hostname" {
  value = "${module.chef-server.chef_server_hostname}"
}

output "supermarket_server_hostname" {
  value = "${module.supermarket-server.supermarket_server_hostname}"
}
```

One spec file is in test/integration/chef_server/controls/chef_server_config_spec.rb
```
describe file('/etc/opscode/chef-server.rb') do
  it { should be_file }
  its('content') { should match(/oc_id/) }
  its('content') { should match(/applications/) }
  its('content') { should match(/supermarket/) }
end

describe file('/etc/opscode/oc-id-applications/supermarket.json') do
  it { should be_file }
  its('content') { should match(/supermarket/) }
  its('content') { should match(/uid/) }
  its('content') { should match(/secret/) }
end
```
test/integration/chef_server/inspec.yml reads:
```
---
name: chef_server
```

And then the other spec file is in test/integration/supermarket_server/controls/supermarket_server_config_spec.rb
```describe file('/etc/supermarket/supermarket.json') do
  it { should be_file }
end
```

Expected behavior:
Because the chef_server_hostname is defined as the only hostname for the chef_server group, the spec file test/integration/chef_server/controls/chef_server_config_spec.rb will only run on the Chef Server hostname.

Because the supermarket_server_hostname is defined as the only hostname for the supermarket_server group, the spec file test/integration/supermarket_server/controls/supermarket_server_config_spec.rb will on run only the Supermarket hostname.

Actual behavior:
The spec files for test/integration/chef_server/controls/chef_server_config_spec.rb  and test/integration/supermarket_server/controls/supermarket_server_config_spec.rb run on BOTH the Chef Server and Supermarket nodes.

Would greatly appreciate any guidance you might have!

**Comment by ncs-alane** [comment]
@nellshamrell you're on the right track, but the group config option is `controls` rather than `tests`.

**Comment by nellshamrell** [comment]
Will give that a try tomorrow :)

**Comment by nellshamrell** [comment]
and ty for the response!

**Comment by ncs-alane** [comment]
@nellshamrell did you have an opportunity to follow up with this?

**Comment by nellshamrell** [comment]
Following up now :)

**Comment by nellshamrell** [comment]
Update - still seeing this issue, even after switching to controls.  Even though I say in .kitchen.yml to only run a certain control on the supermarket server (and not the chef server), it still tries to run that control on both servers.

Here is my current .kitchen.yml
```
---
driver:
  name: terraform

provisioner:
  name: terraform
  variable_files:
    - terraform.tfvars

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: ~/.aws/nshamrell-staging.pem

verifier:
  name: terraform
  format: doc
  groups:
  - name: chef_server
    controls:
      - chef_server_auth
    hostnames: chef_server_hostname
    username: ubuntu
  - name: supermarket_server
    controls:
      - supermarket_server_auth
    hostnames: supermarket_server_hostname
    username: ubuntu

suites:
  - name: default
    run_list:
    attributes:
```

And my current output.tf
```
output "chef_server_hostname" {
  value = "${module.chef-server.chef_server_hostname}"
}

output "chef_server_public_ip" {
  value = "${module.chef-server.chef_server_public_ip}"
}

output "supermarket_server_hostname" {
  value = "${module.supermarket-server.supermarket_server_hostname}"
}

output "supermarket_server_public_ip" {
  value = "${module.supermarket-server.supermarket_server_public_ip}"
}

output "cluster_hostnames" {
  value = "${module.chef-server.chef_server_hostname},${module.supermarket-server.supermarket_server_hostname}"
}
```
And here are the specs - which live in test/integration/default/controls

chef_server_auth_spec.rb
```
control 'chef_server_auth' do
  describe file('/etc/opscode/chef-server.rb') do
    it { should be_file }
    its('content') { should match(/oc_id/) }
    its('content') { should match(/applications/) }
    its('content') { should match(/supermarket/) }
  end

  describe file('/etc/opscode/oc-id-applications/supermarket.json') do
    it { should be_file }
    its('content') { should match(/supermarket/) }
    its('content') { should match(/uid/) }
    its('content') { should match(/secret/) }
  end
end
```

supermarket_server_auth_spec.rb
```
control 'supermarket_server_auth' do
  describe file('/etc/supermarket/supermarket.json') do
    it { should be_file }
  end
end
```

**Comment by ncs-alane** [comment]
It looks like there is a bug with how the profile controls are being specified to the Inspec runner.

**Comment by shinka81** [comment]
@nellshamrell are you also seeing the `chef_server_auth` control being ran on your `supermarket_server` group as well or just the `supermarket_server_auth` control ran on your chef server? I attempted to reproduce the issue you are seeing but I am not getting the same results. Would you mind also posting the terraform output code for `module.supermarket-server.supermarket_server_hostname`? Wondering if multiple hostnames are getting outputted there and possible passed to the group `hostnames` config. I see three nodes tested in my example because the `contrived` groups `hostnames` config has two hosts from its output.

.kitchen.yml
```yaml
---
driver:
  name: terraform
provisioner:
  name: terraform
  variable_files:
    - test/fixtures/credentials.tfvars
transport:
  name: ssh
  connection_retries: 76
verifier:
  name: terraform
  format: doc
  groups:
    - name: different_controls
      controls:
        - ami_id
        - process_ownership
      hostnames: different_host_address
      port: 22
      username: ubuntu
    - name: contrived
      attributes:
        other_host_address: different_host_address
      controls:
        - ami_id
        - reachable_other_host
      hostnames: contrived_hostnames
      port: 22
      username: ubuntu
platforms:
  - name: ubuntu
suites:
  - name: example
```

output.tf
```
output "contrived_hostnames" {
  value = "${module.example.example_1_public_dns}"
}

output "different_host_address" {
  value = "${module.example.example_2_public_ip}"
}
```

controls in test/integration/example/controls

ami_id.rb
```
control 'ami_id' do
  describe ec2_instance.ami_id do
    it { is_expected.to match 'ami-' }
  end
end
```
process_ownership_spec.rb
```
control 'process_ownership' do
  describe processes('init') do
    its('users') { should eq ['root'] }
  end
end
```
reachable_other_host_spec.rb
```
other_host_address = attribute 'other_host_address', {}

control 'reachable_other_host' do
  describe host other_host_address do
    it { is_expected.to be_reachable }
  end
end
```

results:
```
-----> Starting Kitchen (v1.13.2)
       Terraform v0.7.4

-----> Verifying <example-ubuntu>...
       Terraform v0.7.4

       {
           "sensitive": false,
           "type": "string",
           "value": "someIp"
       }
       Verifying host 'someIp' of group 'different_controls'
       Use `/Users/claytonthomas/projects/kitchen-terraform/examples/detailed/test/integration/example` for testing

ami-13be557e
  should match "ami-"

Processes
  users
    should eq ["root"]

Finished in 0.00188 seconds (files took 1.49 seconds to load)
2 examples, 0 failures

       Terraform v0.7.4

       {
           "sensitive": false,
           "type": "string",
           "value": "anIP"
       }
       Terraform v0.7.4

       {
           "sensitive": false,
           "type": "list",
           "value": [
        "someHost.compute-1.amazonaws.com",
        "someHost2.compute-1.amazonaws.com"
           ]
       }
       Verifying host 'someHost.compute-1.amazonaws.com' of group 'contrived'
       Use `/Users/claytonthomas/projects/kitchen-terraform/examples/detailed/test/integration/example` for testing

ami-13be557e
  should match "ami-"

Host 54.242.88.167
  should be reachable

Finished in 0.08248 seconds (files took 3.35 seconds to load)
2 examples, 0 failures

       Verifying host 'someHost2.compute-1.amazonaws.com' of group 'contrived'
       Use `/Users/claytonthomas/projects/kitchen-terraform/examples/detailed/test/integration/example` for testing

ami-13be557e
  should match "ami-"

Host 54.242.88.167
  should be reachable

Finished in 0.06535 seconds (files took 5.06 seconds to load)
2 examples, 0 failures

       Finished verifying <example-ubuntu> (0m5.00s).
-----> Kitchen is finished. (0m5.33s)
```
